<?xml version="1.0" encoding="utf-8"?><Database Name="InventoryManagement" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-GB9EBM46\SQLEXPRESS;Initial Catalog=InventoryManagement;Integrated Security=True;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="InventorySystem.Properties.Settings" SettingsPropertyName="InventoryManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.staff" Member="staffs">
    <Type Name="staff">
      <Column Name="staff_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staff_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staff_Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staff_Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staffRole_ID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="staffStatus_ID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="staff_inventory" Member="inventories" ThisKey="staff_ID" OtherKey="staff_ID" Type="inventory" />
      <Association Name="staffRole_staff" Member="staffRole" ThisKey="staffRole_ID" OtherKey="staffRole_ID" Type="staffRole" IsForeignKey="true" />
      <Association Name="staffStatus_staff" Member="staffStatus" ThisKey="staffStatus_ID" OtherKey="staffStatus_ID" Type="staffStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.itemtype" Member="itemtypes">
    <Type Name="itemtype">
      <Column Name="type_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type_Desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="itemtype_inventory" Member="inventories" ThisKey="type_ID" OtherKey="type_ID" Type="inventory" />
    </Type>
  </Table>
  <Table Name="dbo.inventory" Member="inventories">
    <Type Name="inventory">
      <Column Name="inventory_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="inventory_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stock_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="inventory_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="inventory_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="staff_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="inventory_Remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inventory_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="itemtype_inventory" Member="itemtype" ThisKey="type_ID" OtherKey="type_ID" Type="itemtype" IsForeignKey="true" />
      <Association Name="staff_inventory" Member="staff" ThisKey="staff_ID" OtherKey="staff_ID" Type="staff" IsForeignKey="true" />
      <Association Name="stock_inventory" Member="stock" ThisKey="stock_ID" OtherKey="stock_ID" Type="stock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.staffRole" Member="staffRoles">
    <Type Name="staffRole">
      <Column Name="staffRole_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staffRole_Desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="staffRole_staff" Member="staffs" ThisKey="staffRole_ID" OtherKey="staffRole_ID" Type="staff" />
    </Type>
  </Table>
  <Table Name="dbo.stock" Member="stocks">
    <Type Name="stock">
      <Column Name="stock_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stock_Desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="stock_inventory" Member="inventories" ThisKey="stock_ID" OtherKey="stock_ID" Type="inventory" />
    </Type>
  </Table>
  <Table Name="dbo.staffStatus" Member="staffStatus">
    <Type Name="staffStatus">
      <Column Name="staffStatus_ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staffStatus_Desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="staffStatus_staff" Member="staffs" ThisKey="staffStatus_ID" OtherKey="staffStatus_ID" Type="staff" />
    </Type>
  </Table>
</Database>